theme: jekyll-theme-minimal
title: "Team 21: Team Kaiba Corp"
logo: "https://raw.githubusercontent.com/SapphireLion/p1.21/master/KCLogo.jpg"
description: CS 4331 Project 1 Group Page
show_downloads: true
google_analytics:
